### ISSUE TITLE
Text issue in media player setting

### ISSUE THREAD

**Issue by seantaylorgmi** [OpenVidu/openvidu-call#101]
Hi Team,
First of all, I would like to thank you for developing an amazing WebRTC.

I am having a small issue with openvidu media player.
The problem is with “Go to fullscreen” and “Exit fullscreen” that are available in the settings area.

Initially when I click “Go to fullscreen” it works. After exiting fullscreen using the “Esc” button it works, but the problem is the text in the settings area is still the same.
Please check the attached screenshot.

![OpenviduCall](https://user-images.githubusercontent.com/48057716/128889363-d2401ae1-5d3a-4258-850c-8bdfe1da6dc8.png)

In the above screenshot, I have exited fullscreen using the “Esc” button, but the text in the settings area did not switch back.

I am using openvidu 2.19.0. This issue exists in all versions of openvidu.
Can somebody please help me with this issue?

Thanks for your attention. I’m looking forward to your reply.

**Comment by paimpozhil** [comment]
+1

**Comment by seantaylorgmi** [comment]
Hi
I am using [openvidu-library-angular](https://docs.openvidu.io/en/2.19.0/tutorials/openvidu-library-angular/#openvidu-library-angular) 
Will this issue will be resolved in Openvidu 2.20.0 ?

**Comment by cruizba** [comment]
As far as I can see in the closed commit, it should :)
