### ISSUE TITLE
Issue with output sound in iPhone’s after iOS 15 update

### ISSUE THREAD

**Issue by seantaylorgmi** [OpenVidu/openvidu-call#107]
Hi Team,

First of all, I would like to thank you for developing an amazing WebRTC.

I am facing a new issue after updating my iPhone from iOS 14 to iOS 15.
When I join a video session the publisher’s sound comes out from earpiece (like during a phone call). How can I set output source to a speaker?

I tried enabling speaker layout from media player icons, but nothing seems to be working.
This issue occurs on all Apple iPhones with iOS 15 (Latest version)

I am using [openvidu-library-angular](https://docs.openvidu.io/en/2.20.0/tutorials/openvidu-library-angular/) 2.20.0

Can somebody please help me with this issue?
Thanks for your attention. I’m looking forward to your reply.

**Comment by CSantosM** [comment]
Hi, 
openvidu-angular and openvidu-call have been drastically updated and improved. Now **OpenVidu Components** come into play.

Visit the **OpenVidu Components** documentation [here](https://docs.openvidu.io/en/2.23.0/components/)
Visit the **OpenVidu Call** documentation [here](https://openvidu.io/openvidu-call)
