### ISSUE TITLE
Screen share starts in mirror mode

### ISSUE THREAD

**Issue by yigit-serin** [OpenVidu/openvidu-call#13]
There is no problem at release v1.2.0.
At v2.6.0 screen share starts in mirror mode.

**Comment by pabloFuente** [comment]
Already fixed in development branch of OpenVidu Browser (commits https://github.com/OpenVidu/openvidu/commit/686d6699c960c84f9b089bd1ee8911e415054345 and https://github.com/OpenVidu/openvidu/commit/4cac217d81a02a17311dd971134ee78f2691699a)
