### ISSUE TITLE
Update example to spring security 6.0+, boot 3.2+

### ISSUE THREAD

**Issue by ENate** [OpenVidu/openvidu-call#139]
Will it be okay to try and update this example to spring boot 3.2+ and spring security 6.0+? I will also like to use openvidu on my project. I also will like to work on this issue if I have an approval from you guys. Can you let me know if I can work on it and open a PR? Thanks

**Comment by CSantosM** [comment]
Of course. Feel free to proceed and open the pull request when you're ready.
Thank you

**Comment by ENate** [comment]
No worries :)
