### ISSUE TITLE
Not working as an internal component

### ISSUE THREAD

**Issue by mukesh4718** [OpenVidu/openvidu-call#14]
I have copied all the code to my working Angular 6 project as an internal component. But when I import and use the "OpenviduSessionModule" in root "app.module.ts" the open vidu component is running. When I want to use it as a child component, it always throwing the "Error: RouterModule.forRoot() called twice". Please suggest me how to use it as Child component.
[OpenVidu Angular Library](https://openvidu.io/docs/tutorials/openvidu-library-angular/)

**open-vidu.module.ts**
`import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { OpenViduComponent } from './open-vidu.component';
import { OpenViduRoutes } from './open-vidu.routing';

import { OpenviduSessionModule } from 'openvidu-angular';

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(OpenViduRoutes),
    FormsModule,
    OpenviduSessionModule
  ],
  declarations: [OpenViduComponent],
  exports: [
    OpenViduComponent
  ]
})
export class OpenViduModule {}
`
**open-vidu.component.html**
`<div *ngIf="!session" id="join">
  <div id="join-dialog">
    <h1>Join a video session</h1>
    <form (submit)="joinSession()">
      <p>
        <label>Participant </label>
        <input type="text" id="userName" name="userName" [(ngModel)]="myUserName" required>
      </p>
      <p>
        <label>Session </label>
        <input type="text" id="sessionId" name="sessionId" [(ngModel)]="mySessionId" required>
      </p>
      <p class="text-center">
        <input type="submit" name="commit" value="Join!">
      </p>
    </form>
  </div>
</div>

<div *ngIf="session" id="session">
  <opv-session [sessionName]="mySessionId" [user]="myUserName" [token]="token" (leaveSession)="handlerLeaveSessionEvent($event)"
    (joinSession)="handlerJoinSessionEvent($event)" (error)="handlerErrorEvent($event)">
  </opv-session>
</div>`

**open-vidu.component.ts**
`import { Component, OnInit } from '@angular/core';
import { throwError as observableThrowError } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { HttpClient, HttpHeaders } from '@angular/common/http';
@Component({
  selector: 'app-open-vidu',
  templateUrl: './open-vidu.component.html',
  styleUrls: ['./open-vidu.component.scss']
})
export class OpenViduComponent implements OnInit {
OPENVIDU_SERVER_URL = 'https://' + location.hostname + ':4443';
OPENVIDU_SERVER_SECRET = 'MY_SECRET';

  // Join form
  mySessionId = 'SessionA';
  myUserName = 'Participant' + Math.floor(Math.random() * 100);
  token: string;
  session = false;

  constructor(private httpClient: HttpClient) {}

  joinSession() {
    this.getToken().then((token) => {
      this.token = token;
      this.session = true;
    });
  }

  handlerJoinSessionEvent(event): void {
    // Do something
  }

  handlerLeaveSessionEvent(event): void {
    this.session = false;
  }

  handlerErrorEvent(event): void {
    // Do something
  }

  /**
   * --------------------------
   * SERVER-SIDE RESPONSIBILITY
   * --------------------------
   * This method retrieve the mandatory user token from OpenVidu Server,
   * in this case making use Angular http API.
   * This behavior MUST BE IN YOUR SERVER-SIDE IN PRODUCTION. In this case:
   *   1) Initialize a session in OpenVidu Server	 (POST /api/sessions)
   *   2) Generate a token in OpenVidu Server		   (POST /api/tokens)
   *   3) The token must be consumed in Session.connect() method of OpenVidu Browser
   */

  getToken(): Promise<string> {
    return this.createSession(this.mySessionId).then((sessionId) => {
      return this.createToken(sessionId);
    });
  }

  createSession(sessionId) {
    return new Promise((resolve, reject) => {
      const body = JSON.stringify({ customSessionId: sessionId });
      const options = {
        headers: new HttpHeaders({
          Authorization: 'Basic ' + btoa('OPENVIDUAPP:' + this.OPENVIDU_SERVER_SECRET),
          'Content-Type': 'application/json',
        }),
      };
      return this.httpClient
        .post(this.OPENVIDU_SERVER_URL + '/api/sessions', body, options)
        .pipe(
          catchError((error) => {
            if (error.status === 409) {
              resolve(sessionId);
            } else {
              console.warn('No connection to OpenVidu Server. This may be a certificate error at ' + this.OPENVIDU_SERVER_URL);
              if (
                window.confirm(
                  'No connection to OpenVidu Server. This may be a certificate error at "' +
                    this.OPENVIDU_SERVER_URL +
                    '"\n\nClick OK to navigate and accept it. If no certificate warning is shown, then check that your OpenVidu Server' +
                    'is up and running at "' +
                    this.OPENVIDU_SERVER_URL +
                    '"',
                )
              ) {
                location.assign(this.OPENVIDU_SERVER_URL + '/accept-certificate');
              }
            }
            return observableThrowError(error);
          }),
        )
        .subscribe((response) => {
          console.log(response);
          resolve(response['id']);
        });
    });
  }

  createToken(sessionId): Promise<string> {
    return new Promise((resolve, reject) => {
      const body = JSON.stringify({ session: sessionId });
      const options = {
        headers: new HttpHeaders({
          Authorization: 'Basic ' + btoa('OPENVIDUAPP:' + this.OPENVIDU_SERVER_SECRET),
          'Content-Type': 'application/json',
        }),
      };
      return this.httpClient
        .post(this.OPENVIDU_SERVER_URL + '/api/tokens', body, options)
        .pipe(
          catchError((error) => {
            reject(error);
            return observableThrowError(error);
          }),
        )
        .subscribe((response) => {
          console.log(response);
          resolve(response['token']);
        });
    });
  }

  ngOnInit() {
  }

}
`
**app.module.ts**
import { OpenViduModule } from './open-vidu/open-vidu.module';
@NgModule({
    imports:      [
        ...,
        OpenViduModule
    ],
    declarations: [
        AppComponent,
    ],
    providers: [],
    bootstrap:    [ AppComponent ]
})
export class AppModule { }

**Comment by CSantosM** [comment]
Hi @mukesh4718 ,
The component can be used as a child component. We have checked this following the [openvidu-library-angular](https://openvidu.io/docs/tutorials/openvidu-library-angular/)  tutorial steps:

1) Create a new Angular project with: **ng new openvidu-project**
2) Create a new component with : **ng new component child**
3) Install openvidu-angular: **npm install openvidu-angular --save**
4) Install openvidu-browser: **npm install openvidu-browser --save**
5) Set up [Angular Material](https://material.angular.io/guide/getting-started)
6) Add the Global variable script and Jquery in _index.html_ file:
```
<head>
<!--... other imports ...-->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script>
      var global = global || window;
  </script>
</head>
```
7) Inside of the app.module.ts you must import **OpenviduSessionModule** from _openvidu-angular_:
`import { OpenviduSessionModule } from 'openvidu-angular';`
and inside of imports section of NgModule: `OpenviduSessionModule`

After that, In one hand, in our _app.component.html_ we have included our **child component** with: 
`<app-child></app-child>`

By other hand, inside of **child.component.ts** we will include the following code as we show in [openvidu-library-angular](https://openvidu.io/docs/tutorials/openvidu-library-angular/)  tutorial: 

```
import { Component, OnInit } from '@angular/core';
import { throwError as observableThrowError } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Component({
  selector: 'app-child',
  templateUrl: './child.component.html',
  styleUrls: ['./child.component.css'],
})
export class ChildComponent implements OnInit {
  OPENVIDU_SERVER_URL = 'https://' + location.hostname + ':4443';
  OPENVIDU_SERVER_SECRET = 'MY_SECRET';

  // Join form
  mySessionId = 'SessionA';
  myUserName = 'Participant' + Math.floor(Math.random() * 100);
  token: string;
  session = false;

  constructor(private httpClient: HttpClient) {}

  ngOnInit() {
    this.joinSession();
  }

  joinSession() {
    this.getToken().then((token) => {
      this.token = token;
      this.session = true;
    });
  }

  handlerJoinSessionEvent(event): void {
    // Do something
  }

  handlerLeaveSessionEvent(event): void {
    this.session = false;
  }

  handlerErrorEvent(event): void {
    // Do something
  }

  /**
   * --------------------------
   * SERVER-SIDE RESPONSIBILITY
   * --------------------------
   * This method retrieve the mandatory user token from OpenVidu Server,
   * in this case making use Angular http API.
   * This behavior MUST BE IN YOUR SERVER-SIDE IN PRODUCTION. In this case:
   *   1) Initialize a session in OpenVidu Server	 (POST /api/sessions)
   *   2) Generate a token in OpenVidu Server		   (POST /api/tokens)
   *   3) The token must be consumed in Session.connect() method of OpenVidu Browser
   */

  getToken(): Promise<string> {
    return this.createSession(this.mySessionId).then((sessionId) => {
      return this.createToken(sessionId);
    });
  }

  createSession(sessionId) {
    return new Promise((resolve, reject) => {
      const body = JSON.stringify({ customSessionId: sessionId });
      const options = {
        headers: new HttpHeaders({
          Authorization: 'Basic ' + btoa('OPENVIDUAPP:' + this.OPENVIDU_SERVER_SECRET),
          'Content-Type': 'application/json',
        }),
      };
      return this.httpClient
        .post(this.OPENVIDU_SERVER_URL + '/api/sessions', body, options)
        .pipe(
          catchError((error) => {
            if (error.status === 409) {
              resolve(sessionId);
            } else {
              console.warn('No connection to OpenVidu Server. This may be a certificate error at ' + this.OPENVIDU_SERVER_URL);
              if (
                window.confirm(
                  'No connection to OpenVidu Server. This may be a certificate error at "' +
                    this.OPENVIDU_SERVER_URL +
                    '"\n\nClick OK to navigate and accept it. If no certificate warning is shown, then check that your OpenVidu Server' +
                    'is up and running at "' +
                    this.OPENVIDU_SERVER_URL +
                    '"',
                )
              ) {
                location.assign(this.OPENVIDU_SERVER_URL + '/accept-certificate');
              }
            }
            return observableThrowError(error);
          }),
        )
        .subscribe((response) => {
          console.log(response);
          resolve(response['id']);
        });
    });
  }

  createToken(sessionId): Promise<string> {
    return new Promise((resolve, reject) => {
      const body = JSON.stringify({ session: sessionId });
      const options = {
        headers: new HttpHeaders({
          Authorization: 'Basic ' + btoa('OPENVIDUAPP:' + this.OPENVIDU_SERVER_SECRET),
          'Content-Type': 'application/json',
        }),
      };
      return this.httpClient
        .post(this.OPENVIDU_SERVER_URL + '/api/tokens', body, options)
        .pipe(
          catchError((error) => {
            reject(error);
            return observableThrowError(error);
          }),
        )
        .subscribe((response) => {
          console.log(response);
          resolve(response['token']);
        });
    });
  }
}

```

And inside of **child.component.html** : 

```
<div *ngIf="session" id="session" style="position: absolute; width: 500px; height: 400px;">
  <opv-session [sessionName]="mySessionId" [user]="myUserName" [token]="token" (leaveSession)="handlerLeaveSessionEvent($event)"
    (joinSession)="handlerJoinSessionEvent($event)" (error)="handlerErrorEvent($event)">
  </opv-session>
</div>
```
That's all, it's works.
