### ISSUE TITLE
How to use session variables

### ISSUE THREAD

**Issue by mukesh4718** [OpenVidu/openvidu-call#15]
Thanks for the support

I have integrated openvidu with angular but not able to access core functions provided by openvidu inside angular.

i am using following library https://openvidu.io/docs/tutorials/openvidu-library-angular/

i want to use the following function but do not know how.

This is default function availabe in openvidu browser module.

this.session.on('streamDestroyed', (event: StreamEvent) => {

    // Remove the stream from 'subscribers' array
    this.deleteSubscriber(event.stream.streamManager);
});

**Comment by CSantosM** [comment]
Hello @mukesh4718,
Thank you for the issue. 
Nowadays is not possible to access core functions througth the openvidu-angular library. We will have in mind for the next releases.

**Comment by micaelgallego** [comment]
Access to session variable will be available in the next version. It is already committed to master
