### ISSUE TITLE
Amazon demo  record

### ISSUE THREAD

**Issue by thanatos19808** [OpenVidu/openvidu-call#16]
Hello, I'm setting up the openvidu-call example using the Amazon repository and trying to activate the video recording for a presentation of the technology to my boss. Now configure the /etc/supervisor/conf.d/openvidu.conf file
 and install the docker images but it does not allow me to record. Any idea where I'm failing?

**Comment by pabloFuente** [comment]
OpenVidu Call does not include recording feature by default. You will need to implement it on your own. Should be easy: you can configure your sessions to be automatically recorded or you can start and stop them manually. You do so by configuring the sessions with the proper options when initializing them. This is done in OpenVidu Call by consuming the REST API right in this method: https://github.com/OpenVidu/openvidu-call/blob/master/front/openvidu-call/src/app/shared/services/open-vidu.service.ts#L26-L48

You can add recording configuration options in this line: https://github.com/OpenVidu/openvidu-call/blob/master/front/openvidu-call/src/app/shared/services/open-vidu.service.ts#L29
Follow parameters guidelines here stated: https://openvidu.io/docs/reference-docs/REST-API/#post-apisessions

And, of course you will need to launch OpenVIdu Server with recording module enabled. If you are using  our Amazon deployment, then OpenVidu Server is already enabled and properly configured. Just modify OpenVIdu Call application to record your sessions and should work fine.

Regards

**Comment by ashutoshmishraji** [comment]
i  have same issue and i also read above solution but i did not understood 
Please help me

**Comment by micaelgallego** [comment]
OpenVidu Call demo app doesn't support recording. You will need to modify it to use recording feature.
