### ISSUE TITLE
Demo don't works

### ISSUE THREAD

**Issue by marciocamello** [OpenVidu/openvidu-call#18]
This resource are offline

https://demos.openvidu.io/openvidu-call/ov-settings.json

**Comment by CSantosM** [comment]
Hello, 
Demo is working.
You can provide the optional resource  **ov-settings.json** in your OpenVidu Call app. 
We have documented it at the ond of [this tutorial](https://openvidu.io/docs/demos/openvidu-call/).
Regards.

**Comment by redskate** [comment]
https://demos.openvidu.io/openvidu-call does not work 

There was an error getting the token:
Http failure response for https://demos.openvidu.io:4443/api/sessions: 0 Unknown Error.

And neither the current docker version works (same error).

**Comment by micaelgallego** [comment]
Due to a traffic peak, our demos have suffered some outage. We have increased their capacity and they are up again.
