### ISSUE TITLE
Testing demos

### ISSUE THREAD

**Issue by okdzhimiev** [OpenVidu/openvidu-call#19]
Hello, 

Is there any demo that would allow to place a basic video call between 2 laptops?

I'm on Kubuntu 18.04. Have tried a couple demos from https://openvidu.io/demos:

**1. github:**
* [openvidu-call](https://openvidu.io/docs/demos/openvidu-call/)
* [openvidu-call-react](https://openvidu.io/docs/demos/openvidu-call-react/)
* [openvidu-call-ionic](https://openvidu.io/docs/demos/openvidu-call-ionic/)

Only **master** branches. Are they normally broken?

**2. dockerhub:**
> docker run -t --name openvidu-call -e OV_PROFILE=ngrok -p 4443:4443 openvidu/openvidu-call

**latest** does not work?

**3. online demo:**

https://demos.openvidu.io/openvidu-call
Only chat works. No video, no screensharing

Thanks.

**Comment by pabloFuente** [comment]
Ok, first things first. If your not able to establish video sessions in _demos.openvidu.io_, then I'm sure you will also have problems to use any other WebRTC based application. Maybe you have an extremely restrictive firewall, because all demos properly work in every other network we (and many other users) have tried: 4G mobile networks, UDP restricted corporate networks, any private WiFi netwroks...
Try other videoconferencing services (https://getaroom.io, https://appear.in ...) and see if they work fine.

**Comment by okdzhimiev** [comment]
* appear.in works fine - able to see other laptop's video.
* Using Firefox 64.0 (64bit)
* With [openvidu-call](https://demos.openvidu.io/openvidu-call) in dev console I get:
 > ICE failed, see about:webrtc for more details

Yes, I'm behind a firewall. Will try from home and let you know.
Thanks.

**Comment by okdzhimiev** [comment]
Tried at home with a laptop and an android phone - each device plays its own video only, chat works both ways.

**Comment by VolanDeVovan** [comment]
same issue

**Comment by micaelgallego** [comment]
Hi @VolanDeVovan,
Can you describe exactly what is your problem?

**Comment by alecpl** [comment]
Is there a way to configure `iceServers`? Normally you could do:
```
    OV.setAdvancedConfiguration({
            iceServers: [{ urls: "stun:test.server.com:3478" }]
    })
```

**Comment by pabloFuente** [comment]
What is the question? You already answered it yourself.

**Comment by alecpl** [comment]
I don't see how to do this without changing the code of webcomponent or the openvidu-call app.

**Comment by pabloFuente** [comment]
Ok, so you want to manually configure the iceServers in openvidu-call.

I think the current version does not allow doing this through the json configuration file. But I think we can study it.

**Comment by micaelgallego** [comment]
You have to change the code and regenerate the component.
