### ISSUE TITLE
Throwing error after building

### ISSUE THREAD

**Issue by Jagdeep-Sing** [OpenVidu/openvidu-call#20]
When i run `ng serve --open` it is building up to 100% . After building its throwing following error: <br><br>

> (node:28587) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/var/www/html/conitor/sys/openvidu-call/front/openvidu-  call/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:28587) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28587) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CSantosM** [comment]
Hello @Jagdeep-Sing 
We have ran ```ng serve --open``` and it's working fine, We aren't be able to reproduce your problem.

The origin of this error lies in the fact that each and every promise is expected to handle promise rejection. We have added ```.catch()``` in each promise. Check it out and post here your results, please.
Thanks.

**Comment by Jagdeep-Sing** [comment]
I cloned the repository again and its throwing same error: <br>
![openvidu](https://user-images.githubusercontent.com/25609915/51974316-aea89b80-24a5-11e9-9c2e-6176e6405bf1.png)

**Comment by CSantosM** [comment]
We need some more information...
Could you run ```ng --version``` and  ```npm --version ``` and tell us the result please?

**Comment by Jagdeep-Sing** [comment]
@CSantosM can you please help on this ?

**Comment by CSantosM** [comment]
I'm sorry @Jagdeep-Sing but we can't reproduce your problem. The project is working fine.
You should try to install the latest version of typescript, npm, node and angular cli in your computer and clone the project again. 
Thank you.

**Comment by pabloFuente** [comment]
What OS are you using to compile the project? Maybe there's some combination of OS and packages versions that's causing this issue.

**Comment by Jagdeep-Sing** [comment]
@CSantosM Okay
@pabloFuente  I am on ubuntu 16

**Comment by Jagdeep-Sing** [comment]
Its compiling without error when i run:  `ng server` <br>
and <br>
throwing error when i run : `ng serve --open` <br>
Given ports are open but unable to access it from browser

**Comment by Jagdeep-Sing** [comment]
I think there is some error in the way i'm building it
I deployed on ec2 and got same error

What im doing is :

KMS is running on server and openvidu frontend is also accessible on port 4443

after that i cloned this repo
node & angular are installed already
then
cd openvidu-call/front/openvidu-call
npm install
then
ng serve --open

and error came.

Is this the right way or i am missing something here ?
