### ISSUE TITLE
Screen sharing works only once

### ISSUE THREAD

**Issue by iiiyx** [OpenVidu/openvidu-call#23]
version 2.11.0
**Steps**:
1. open https://demos.openvidu.io/openvidu-call/
2. start a call
3. start a screen sharing
4. stop a screen sharing
5. start a screen sharing again

**Expected results**:
iceCandidates are successfully added 

**Actual results**:
iceCandidates are not added
error in console: _TypeError: Cannot read property 'addIceCandidate' of undefined_
this error is located in _Session.prototype.recvIceCandidate_ function on _stream.getWebRtcPeer().addIceCandidate(candidate)_ call: _Stream.webRtcPeer_ is _undefined_

**Comment by iiiyx** [comment]
Also, I have noticed that the screen sharing participants (connections) are not triggering participantLeft event, they are triggering only participantUnpublished event. Thus they stay at a call. Maybe there is some error in stopping screen sharing which leads to iceCandidates error, described above.

**Comment by SlavaOST** [comment]
had same issue in my installation.

**Comment by CSantosM** [comment]
Also replicated in openvidu-angular-library issue [#77](https://github.com/OpenVidu/openvidu-tutorials/issues/77)

**Comment by janelin612** [comment]
I had same issue, and solved it successfully. 
But I am not sure the way is correct or not.

I modified the method `getConnection` in `\openvidu-browser\src\OpenVidu\Session.ts` . 
I exchanged the first block and second block in if-else so it will resolve local connection first.
