### ISSUE TITLE
Closing session keeps WebSocket Open indefinitely

### ISSUE THREAD

**Issue by tfurst86** [OpenVidu/openvidu-call#24]
It seems that upon closing a video session, Kurento keeps a websocket open until a full on OS reboot of the Kurento server. Restarting kurento keeps the keepAlive running, but it recognizes that the session "Should be removed". We do not see this problem with Kurento WebRTC calls as closing the client stops the keepAlive. Is there something missing from the close in this package that completely sends a kill command to Kurento?

Tested with Kurento 6.11 and 6.12 vanilla builds.

**Comment by CSantosM** [comment]
Kurento has been upgraded to 6.13.1. Check it out an open a new issue if you taste the same behavior.
