### ISSUE TITLE
Docker openvidu-call & SSL certificate

### ISSUE THREAD

**Issue by redskate** [OpenVidu/openvidu-call#28]
Testing this nice app on a virtualized ubuntu 18 - server WITHOUT any firewall, hence with every port open.

using docker openvidu/openvidu-call (see below)

Since I would like to have a clean SSL transmission, I have an own keystore, I figured out how to to add environment segments to the suggested docker run command:

`docker run -p 4443:4443 -e openvidu.publicurl=https://IPXXX:4443/ -e server.ssl.key-store=/etc/my.keystore.p12 -e server.ssl.key-store-password=thepasswd -e server.ssl.key-store-type=PKCS12 -e ssl.key-alias=onlymine    openvidu/openvidu-call`

An exception tells that /etc/my.keystore.p12 does not exists (but it it searching INSIDE the docker container, hence all-right sofar) and the application fails.

How should I call openvidu-call via docker (as you recommended) in order to take my SSL keystore? I guess there must be some volume there ... which volume should I use ?

If this is "not possible" ;) I would at least know whether there can be any HTTP port I could expose in order to re-wash it via nginx in SSL. Thanks!!!

**Comment by redskate** [comment]
As I see, no one can answer this ... in time. Pity.

**Comment by micaelgallego** [comment]
We are working right now in an improved version of openvidu-call docker image including coturn and with more documentation on how to configure things.

Please stay tuned.
