### ISSUE TITLE
Work with only 1 user

### ISSUE THREAD

**Issue by albevt** [OpenVidu/openvidu-call#31]
Hi, i build openvidu-call and upload on my dev server, the client work with only 1 user, when second user on the login page insert the same me room name he join in the session without video and audio, but the chat work. On the second user browser console i find an error to my openvidu-server url /api/session :
409
Versione:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

HTTP/1.1 409 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: *
Set-Cookie: JSESSIONID=31E2E0F38A7634497B979D0D40DA9D3C; Path=/; Secure; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
Content-Length: 0
Date: Mon, 16 Mar 2020 19:40:33 GMT

**Comment by micaelgallego** [comment]
Please describe how have you deployed OpenVidu server.

Have you followed these instructions? https://openvidu.io/docs/deployment/deploying-ubuntu/

Docker container can not be used to deploy OpenVidu for production usage because a TURN server is needed.

**Comment by albevt** [comment]
Hi, i deployed openvidu server with this docs on ubuntu 18.04 https://openvidu.io/docs/deployment/deploying-ubuntu/, i use with success openvidu-client insecure angular

**Comment by albevt** [comment]
Resolved with update openvidu-server to the latest version.
thank's
