### ISSUE TITLE
Cannot find module '. . . @angular/cli/bin/postinstall/script.js'

### ISSUE THREAD

**Issue by brailateo** [OpenVidu/openvidu-call#33]
root@~/openvidu-call# uname -a
Linux 4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linu

root@~/openvidu-call# node -v
v12.16.1

root@~/openvidu-call# npm -v
6.13.4

Just "git cloned" openvidu-call 2 minutes ago!
When npm install in ~/openvidu-call/front/openvidu-call

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@9.0.6 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @angular/cli@9.0.6 postinstall script.

**Comment by CSantosM** [comment]
Hello @brailateo ,

I just cloned the repo and to execute npm install and it's working. 

Do you have angular cli installed?

**Comment by brailateo** [comment]
I'll try the whole process on a fresh, new installed Ubuntu 18.04.4 server! Thanks!
