### ISSUE TITLE
Problem when mixing iOS and non iOS clients

### ISSUE THREAD

**Issue by slabajo** [OpenVidu/openvidu-call#34]
We have identified two related problems that arise when there is a session with many users (above 6) and just one or two are iOS client (Safari). We observe the following:
- On the server there are several transcodings simultaneous that consume a lot of CPU, probably due to the fact that iOS browser chooses with preference H.264 codec over VP8 whereas non iOS browsers tend to choose VP8 over H.264. This causes probably uneeded transcodings. Uneeded, because Safari supports VP8 and Chrome and Firefox support H.264
- But we also observe something on the client, specifically on the iOS client, when there are several participants non iOS, the browser in the iOS phone gets overloaded too soon, w make the hypothesis that this is due that iOS Safari may be decoding VP8 by software (using the CPU). Even up to the point of not beign able to respond to websocket ping from openvidu server. Which in turn causes OpenVidu server to evict the iOS phone participant.

So, in the end, would it be possible to force or choose a codec priority? I mean regardless of the codecs priority offered by the browsers, could it be possible to, for example, choosing H,264, as the preferred codec so that if possible all participants use H,264, avoiding transcoding at all and making possible for iOS to use the hardware H,264 decoder.

**Comment by micaelgallego** [comment]
Thank you for reporting Saúl. 

The best way to force H264 is removing VP8 negotiation in Kurento Media Server. Can you test if that solves the CPU peak usage and performance problems in OpenVidu?

Use
```
"videoCodecs": [
    { "//name": "VP8/90000" },
    { "name": "H264/90000" }
]
```
in `/etc/kurento/modules/kurento/SdpEndpoint.conf.json`
