### ISSUE TITLE
echo cancellation

### ISSUE THREAD

**Issue by viktara** [OpenVidu/openvidu-call#35]
Just checking if there are any plans to implement software echo cancellation?

**Comment by micaelgallego** [comment]
Echo cancelation is implemented in WebRTC stack of browsers. If you have echo problems, please describe your issue.

**Comment by viktara** [comment]
Sure it's implemented by the browser, but there are a  number of options provided by different browsers.
In my case, echo makes openvidu-call unusable on firefox or chromium on android
Similarly on both browsers on Linux.
Works find if you use echo cancelling hardware.

**Comment by viktara** [comment]
I can do some debugging on firefox / linux.
on the about:webrtc tab you can run out AEC debug logs

**Comment by viktara** [comment]
After doing some testing this afternoon, the issue is actually quite particular and probably not as I have described it above.

AEC is in fact working correctly on the desktop browser.

The problem seems particular to the mobile browser when using speaker phone. It's slightly understandable as the recording level of the speakerphone would be quite high, however, AEC should still kick in.

I cannot test this on firefox mobile however, there seems to be a bug in openvidu-call where it does not allow you to select a speaker phone.

Chromium allows you to select a speaker phone and this is where you will experience the lack of ech cancellation.

**Comment by CSantosM** [comment]
Hello,  
Are you are you testing OpenVidu call from master? Or are you testing OpenVidu Call 2.12.0?

**Comment by viktara** [comment]
2.12.0 - we're about to upgrade to the latest beta, but instead i'll get a build from master if that helps

**Comment by CSantosM** [comment]
You shouldn’t have this problem on v2.13.0-beta8 or getting OpenVidu Call from master.

**Comment by CSantosM** [comment]
Problem should be solved. Open a new issue if it comes up again
