### ISSUE TITLE
Max number of participants in the same session

### ISSUE THREAD

**Issue by viktara** [OpenVidu/openvidu-call#38]
Going by the load testing it seems that there is a preferred limit of conference participants.
I have managed 18 people in a conference but it did lead to kurento not responding and the server crashing under load.
Any pointers that you would have of where to look to improve the performance of this aspect of the app?

**Comment by micaelgallego** [comment]
Video conferences demand high computational resources. We are focused right now on improving stability in sessions with a high number of participants.

We have used OpenVidu Call with 22 participants in the same session in a 4 CPU machine without issues.

**Comment by viktara** [comment]
could you give any pointers as to exactly where the work needs to happen so that we can collaborate?  I can offer help with testing, anything in angular, anything in java

**Comment by viktara** [comment]
> Video conferences demand high computational resources. We are focused right now on improving stability in sessions with a high number of participants.
> 
> We have used OpenVidu Call with 22 participants in the same session in a 4 CPU machine without issues.

Hmm, did everyone use the same browser in that session?

**Comment by micaelgallego** [comment]
We have executed tests with Google Chrome.

We are working on improve the efficiency of the platform, but WebRTC is very resource consuming technology.
