### ISSUE TITLE
There was an error getting the token cannot POST/call

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu-call#40]
Hi Carlos,

When i tap join button it will getting below error.

![image](https://user-images.githubusercontent.com/6995567/80198656-08aef700-863e-11ea-9615-c9a0d7b0ea57.png)

Still in package json showing Openvidu-Browser 2.12.0

"dependencies": {
    "@angular/animations": "9.1.0",
    "@angular/cdk": "9.2.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/elements": "9.1.0",
    "@angular/flex-layout": "9.0.0-beta.29",
    "@angular/forms": "9.1.0",
    "@angular/material": "9.2.0",
    "@angular/platform-browser": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/router": "9.1.0",
    "core-js": "3.1.4",
    "jquery": "3.4.1",
    "ngx-linkifyjs": "1.3.0",
    **"openvidu-browser": "2.12.0",**
    "rxjs": "6.5.4",
    "unique-names-generator": "4.2.0",
    "zone.js": "0.10.3"
  },

**Comment by CSantosM** [comment]
Hi, 

We're working on get better OpenVidu Call and we're developing hard changes. 
We'll document all this changes when v2.13.0 is released. Meanwhile, please, use the **v2.12.0 stable** version.

It'll be released the next week.

Stay tuned.
Regards
