### ISSUE TITLE
There were an error getting token when i tap join button

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu-call#41]
Hi Carlos,

When i tap Join button getting below error. How can i connect methods in openvidu-call-back  to openvidu-call-front.

![image](https://user-images.githubusercontent.com/6995567/80212282-d1981000-8654-11ea-9114-4a24eab6322b.png)

**Comment by surya5353** [comment]
Duplicate

**Comment by nirbhaydosi** [comment]
I am also facing the same issue.
