### ISSUE TITLE
externalConfig becomes undefined

### ISSUE THREAD

**Issue by vinayakvinay** [OpenVidu/openvidu-call#47]
I wanted to customize the **ovServerUrl** and **ovSecret**.
Where should we make the changes in the Angular application? Please help. 

ExternalConfig becomes undefined for me...

![Screen Shot 2020-05-04 at 11 39 42 PM](https://user-images.githubusercontent.com/13932031/80998541-bef5b600-8e60-11ea-9a75-073616919b1c.png)

**Comment by CSantosM** [comment]
Issue tracker is just for issues and bugs. 
Use [OpenVidu Forum](https://openvidu.discourse.group/) instead.
