### ISSUE TITLE
Could not resolve openvidu-angular relative to [object Object]..

### ISSUE THREAD

**Issue by raoadnankhan** [OpenVidu/openvidu-call#48]
I am building using openvidu-angular v2.14.0 with angular 9.1.0 and getting this error.  I have cleaned node_modules multiple times but same error when trying to load the package. Here is my ts statement that is giving error:

import { OpenviduSessionModule } from 'openvidu-angular';

looking forward for your assistance.

**Comment by CSantosM** [comment]
Hi @raoadnankhan ,
Could you share your error with us  please?

**Comment by CSantosM** [comment]
@raoadnankhan  yes, you're completelly right.

We'll fix it ASAP.

Thanks for your report

**Comment by CSantosM** [comment]
Hello @raoadnankhan,

Try with [2.14.1](https://www.npmjs.com/package/openvidu-angular/v/2.14.1). The problem should be fixed.

**Comment by raoadnankhan** [comment]
Yes, it does fix it. Thanks for a quick turn around.
