### ISSUE TITLE
Requests for images from outside

### ISSUE THREAD

**Issue by ecmel** [OpenVidu/openvidu-call#50]
Hi, thank you for the fantastic app.

There are some requests outside of my domain for the following assets in the setup screen:

https://openvidu.io/img/logos/openvidu_globe_bg_transp_cropped.png

https://openvidu.io/img/logos/openvidu_globe_bg_transp_cropped.png

https://raw.githubusercontent.com/OpenVidu/openvidu-call/master/openvidu-call-front/src/assets/images/openvidu_logo.png

**Comment by micaelgallego** [comment]
You can change the source code of OpenVidu Call to include your own images if you want.

**Comment by pabloFuente** [comment]
But I guess that including those images as local resources of the app would be the way to go

**Comment by ecmel** [comment]
Those assets are already in the release archive
