### ISSUE TITLE
Option to show no-video participant slot

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [OpenVidu/openvidu-call#51]
Hello!

OpenVidu Call 2.14 comes with a feature to hide no-video participants in the grid. This is a nice feature in most situations, but I think it should be toggleable to reach all situations. For example, today one of our team used OpenVidu Call for a daily meeting. That team has 6 participants, but only the team leader uses an enabled webcam. All other participants don't enable their webcams.

The feedback the leader gave to me is that not knowing who is on the room in a clear way was not good. I understand OpenVidu Call shows at the bottom a list of participants, but I think a blank state slot would represent better who is participating in this specific situation.

In order to not just show an empty black slot, a blank state slot (with a nice svg of a generic avatar) would be a nice fit. This way it will make clear to everyone that the participant with disabled cam is not streaming video. If the slot is just a black background, some users may think the participant is having trouble streaming it's video.

Could OpenVidu Call have a option to toggle this feature per room?

Best regards,
Rafael Pacheco.

**Comment by CSantosM** [comment]
Hi @rafaelrenanpacheco ,

I understand your view, we will consider including this toggle feature in the next release.
