### ISSUE TITLE
Mute All option is available in 2.14 ?

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu-call#52]
Hi Team,

Looking good all things in 2.14.
I am using openvidu call angular application. Can we mute all participants except speaker, is this option available in this patch, or suggest me how to handle that with custom code.

when share my screen its works fine. When we tap on default chorme stop share button video state still black area in others as well as my side. Once i tap on openvidu screenshare stop button then it will disappear.  How to handle both actions are do same activity.

**Comment by micaelgallego** [comment]
If you want to mute all participants, you have to modify the code of application. It is not provided out of the box.

For close screen share automatically, you can add the following event handler: 
https://docs.openvidu.io/en/2.14.0/advanced-features/screen-share/#how-to-know-when-the-user-stops-sharing-the-screen

**Comment by topninja** [comment]
If you want to mute all participants, you have to modify the code of application. It is not provided out of the box.

can u explian little detail about this?
thanks
