### ISSUE TITLE
How to move entire openvidu call project into another module ?

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu-call#53]
Hi Team,
I am using openvidu call angular.
I want to try move entire openvidu call files into separate module. Please let me help the steps for that. Or any alternative i used only web component into other module but its not working.

**Comment by CSantosM** [comment]
I don't thinkg this is a openvidu-call bug

**Comment by micaelgallego** [comment]
You need Angular programming skills to do it.

**Comment by surya5353** [comment]
Thank you. I will try it.

**Comment by micaelgallego** [comment]
You can take a look to OpenVidu-Library-Angular, as it is a library encapsulated that you can use in other projects:

https://docs.openvidu.io/en/2.14.0/tutorials/openvidu-library-angular/
