### ISSUE TITLE
There was an error getting the token cannot POST/call

### ISSUE THREAD

**Issue by AngeloLDias** [OpenVidu/openvidu-call#54]
Hello,

![image](https://user-images.githubusercontent.com/37551237/82416090-e008fa00-9a4f-11ea-9644-5bbc4453aa15.png)

returns this error when I post to '/ call'

my help please

**Comment by CSantosM** [comment]
We need more information about this error. 
Please could you describe every single detail of how are you deploy openvidu, where, which version, browser console, Openvidu, nginx, and openvidu call logs and every important thing

**Comment by AngeloLDias** [comment]
segue a baixo,

![image](https://user-images.githubusercontent.com/37551237/82422307-aa1c4380-9a58-11ea-93c1-a30c58d86ead.png)

![image](https://user-images.githubusercontent.com/37551237/82422346-b56f6f00-9a58-11ea-84ec-05ad3b7f528c.png)

![image](https://user-images.githubusercontent.com/37551237/82422438-d33cd400-9a58-11ea-9568-3f6281f915fe.png)


{
    "dependencies": {
        "@angular/animations": "9.1.4",
        "@angular/cdk": "9.2.1",
        "@angular/common": "9.1.4",
        "@angular/compiler": "9.1.4",
        "@angular/core": "9.1.4",
        "@angular/elements": "9.1.4",
        "@angular/flex-layout": "9.0.0-beta.29",
        "@angular/forms": "9.1.4",
        "@angular/material": "9.2.1",
        "@angular/platform-browser": "9.1.4",
        "@angular/platform-browser-dynamic": "9.1.4",
        "@angular/router": "9.1.4",
        "core-js": "3.1.4",
        "jquery": "3.5.0",
        "ngx-linkifyjs": "1.3.0",
        "openvidu-browser": "2.14.0",
        "rxjs": "6.5.5",
        "unique-names-generator": "4.2.0",
        "zone.js": "0.10.3"
    },

**Comment by taymur1** [comment]
I have same error

**Comment by CSantosM** [comment]
We need more information about this error.

Please could you describe every single detail of how are you deploy openvidu? 
Also we need the following logs for understand your problem
-  Browser logs
- Openvidu Server logs 
- Nginx logs
- OpenVidu Call logs

**Comment by CSantosM** [comment]
Close for inactivity
