### ISSUE TITLE
2.14 Screen Share unable to stop with browser default stop button.

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu-call#57]
Hi,
Please check below screenshot. When we tap on browser stop share button screenshare stopped but video state still stay on... and showing blank screen.
Below screenshot start screenshare.
![image](https://user-images.githubusercontent.com/6995567/83109457-13e2c000-a0df-11ea-9c1b-fef00281bedc.png)

Below screeshot is stop screenshare with browser stop button. At this time you observe still openvidu screenshare button is enabled. but screenshare closed and black empty screen shows. Again we tap on openvidu stop sreenshare icon then empty black screen gone.
![image](https://user-images.githubusercontent.com/6995567/83109646-5c9a7900-a0df-11ea-91bb-4cbe058364e7.png)

I also use this way but not working.
https://docs.openvidu.io/en/2.14.0/advanced-features/screen-share/#how-to-know-when-the-user-stops-sharing-the-screen

I used below both ways 
![image](https://user-images.githubusercontent.com/6995567/83110101-2d383c00-a0e0-11ea-8f35-115f969e528e.png)

**Comment by CSantosM** [comment]
This is added in master ([this commit](https://github.com/OpenVidu/openvidu-call/commit/38d5a0391ab87f0cec76a02e964b4b1dfa876f6e)) and included in the next release.

**Comment by surya5353** [comment]
> This is added in master ([this commit](https://github.com/OpenVidu/openvidu-call/commit/38d5a0391ab87f0cec76a02e964b4b1dfa876f6e)) and included in the next release.

Done. Thank you. 
I already asked you  one more thing. let me give suggestion. 

If i share screen looks like below 
![image](https://user-images.githubusercontent.com/6995567/83127682-14d41b80-a0f8-11ea-9794-d17ab72ccca7.png)


and at the same time other participant also shared screen. how we can share the screen one time only.

**Comment by pabloFuente** [comment]
A bunch of people have already asked this same question, and I don't quite understand what the misunderstanding is on this subject... If you share a screen and in that same screen you show the application that is screen-sharing, you get that infinite fractal image. Not an OpenVidu thing, not a WebRTC thing and not even a technological thing. It is pure physics:

![nickieatmirror](https://user-images.githubusercontent.com/15049534/83128868-4b9c3880-a0dc-11ea-8dc1-3ebfbd764728.jpg)

**Comment by surya5353** [comment]
> A bunch of people have already asked this same question, and I don't quite understand what the misunderstanding is on this subject... If you share a screen and in that same screen you show the application that is screen-sharing, you get that infinite fractal image. Not an OpenVidu thing, not a WebRTC thing and not even a technological thing. It is pure physics:
> 
> ![nickieatmirror](https://user-images.githubusercontent.com/15049534/83128868-4b9c3880-a0dc-11ea-8dc1-3ebfbd764728.jpg)

**I am 100% accept and agree with you.** 
Thats what i asked is any suggestion for that from you guys. Once you see google meet, zoom or skype. here we have no problem and they are restricted or other screen showing in that scenario. I am just asking you bro. It you guys working on this it will more quality product na so. see below screenshot from google meet. I not comparing with ours to google. If it is possible you can also done in openvidu so.. please take this only suggestion

![image](https://user-images.githubusercontent.com/6995567/83129655-c1af9800-a0fa-11ea-9c86-320a5b04743c.png)
.

**Comment by pabloFuente** [comment]
Oh, so you are just suggesting that the local shared screen is simply not shown.... It's something to think about. Because sometimes it is useful for the presenter to have the preview of what other users are currently seeing, even if this behavior appears when showing the shared screen. Don't know, maybe we should take a poll and see what people think about it.
