### ISSUE TITLE
UNKNOWN nickname in video stream

### ISSUE THREAD

**Issue by endo199** [OpenVidu/openvidu-call#58]
Version:
openvidu-angular: 2.14.2
openvidu server: 2.13.0
-------
If I send payload of {session: '', role: 'PUBLISHER', **data: 'something'**} to _/api/tokens_ and then join  a room; the first person who join the room will always see nickname of several other participants as **unknown**. 

When I trace to **RemoteUsersService.ts** in _add()_ function
`try {
			nickname = JSON.parse(event.stream.connection.data)?.clientData;
			avatar = JSON.parse(event.stream.connection.data)?.avatar;
		} catch (error) {
			nickname = 'Unknown';
		}`

because value of _event.stream.connection.data_ will have **%/%something**; thus it can't be parsed and will caused an error which resolve the nickname to unknown.

**Comment by CSantosM** [comment]
Have you tested to send the user property to the library? 

```
<opv-session
  #ovSessionComponent
  [sessionName]="mySessionId"
  [user]="myUserName" < ------------------------ this property
  [tokens]="tokens"
  [ovSettings]="ovSettings"
  (sessionCreated)="handlerSessionCreatedEvent($event)"
  (publisherCreated)="handlerPublisherCreatedEvent($event)"
  (error)="handlerErrorEvent($event)">
</opv-session>
```

**Comment by endo199** [comment]
Yes, although I set the username from an attribute inside of user object. So, I set like this
[user] = "user?.name"

**Comment by micaelgallego** [comment]
Please set a literal name just in case "user" is null or undefined.
