### ISSUE TITLE
Add ip camera but name :unknown

### ISSUE THREAD

**Issue by volkankoc** [OpenVidu/openvidu-call#59]
hi team

I'm adding a rtsp camera. Although I name it with data it turns out to be unknown
example body
`{
"type": "IPCAM", 
"rtspUri": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov", 
"adaptativeBitrate": true, 
"onlyPlayWithSubscribers": true, 
"data": "IP Camera"
}
`
but  camera name unknown
use tutor 
https://docs.openvidu.io/en/2.14.0/reference-docs/REST-API/#post-apisessionsltsession_idgtconnection

**Comment by CSantosM** [comment]
OpenVidu Call needs receive a metadata named `clientData` with the user nickname .

`ovSession.connect(token, { clientData: 'nickname' });`
