### ISSUE TITLE
How to record videocalls in openvidu-call demo?

### ISSUE THREAD

**Issue by le8888e** [OpenVidu/openvidu-call#62]
Hello,

I try to record videocalls in this demo.  I followed the instruction here https://docs.openvidu.io/en/2.14.0/advanced-features/recording/
But I can't get the recording file. 

First I start openvidu server by running:
docker run -p 4443:4443 --rm \
    -e OPENVIDU_RECORDING=true \
    -e OPENVIDU_RECORDING_PATH=/PATH/TO/VIDEO/FILES \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES \
openvidu/openvidu-server-kms:2.14.0

Should all the three '/PATH/TO/VIDEO/FILES' be exactly the same ?

Then I ran the backend:
When create session I add a parameter recordingMode: "ALWAYS" in request body 

Last I ran the front end.

Here are the  port numbers:
openvidu server: 4443
backend: 5000
frontend: 4200

The terminal of backend keep logging Requesting session to https://localhost:4443/api/sessions and never goes to createToken.

Could you tell me what's probably going wrong? 
Thank you.

**Comment by CSantosM** [comment]
Hi,

Do you have any error in your browser or backend console? 
Could you share it with us?

**Comment by le8888e** [comment]
Hi @CSantosM,

I have fixed the problem. The problem is caused since I didn't correctly invoke creakeToken().

Thank you.
