### ISSUE TITLE
How to enable multi-people openvidu-call?

### ISSUE THREAD

**Issue by le8888e** [OpenVidu/openvidu-call#63]
Hi,

I tried openvidu-call  demo by following the instruction:
https://docs.openvidu.io/en/2.14.0/demos/openvidu-call/

The instruction only shows how to start a local openvidu server and build an app on local host.
But how to enable multi-people calls? What should be done on other hosts to join the session?

Thanks a lot.

**Comment by CSantosM** [comment]
I dont know what do you mean with "how to enable multi-people calls".

If you want to deploy OpenVidu Call, you have to read https://docs.openvidu.io/en/2.14.0/deployment/.

By the way, the issue tracker is just for issues and this is not an error of OpenVidu Call, use OpenVidu Forum instead.
