### ISSUE TITLE
There was an error getting the token

### ISSUE THREAD

**Issue by nirbhaydosi** [OpenVidu/openvidu-call#64]
OpenVidu v2.14.0,

I am getting below error while I click to join button.

Front-End Error - 

There was an error getting the token:
Cannot connect with backend. http://localhost:4200/call not found.

Backend-Error -

Requesting session to  http://localhost:4200/api/sessions
Error: Request failed with status code 404

below is config.ts file configuration,

export const SERVER_PORT = process.env.SERVER_PORT || 5000;
export const OPENVIDU_URL = process.env.OPENVIDU_URL || 'http://localhost:4200';
export const OPENVIDU_SECRET = process.env.OPENVIDU_SECRET || 'MY_SECRET';
export const CALL_OPENVIDU_CERTTYPE = process.env.CALL_OPENVIDU_CERTTYPE;

Front-End is running with 4200 port with localhost.

If anyone knows this issue then please reply to me here.

**Comment by CSantosM** [comment]
Have you read and followed this https://docs.openvidu.io/en/2.14.0/demos/openvidu-call/#get-and-execute-the-code ?

**Comment by nirbhaydosi** [comment]
Yes, I have read this and I am not using docker.

But below configuration is correct ?

export const SERVER_PORT = process.env.SERVER_PORT || 5000;
export const OPENVIDU_URL = process.env.OPENVIDU_URL || 'http://localhost:4200';
export const OPENVIDU_SECRET = process.env.OPENVIDU_SECRET || 'MY_SECRET';
export const CALL_OPENVIDU_CERTTYPE = process.env.CALL_OPENVIDU_CERTTYPE;

**Comment by CSantosM** [comment]
The instructions I posted are not about docker, it’s about how run correctly openvidu call. 

As the docs says, step 3, you need run openvidu-server container to do openvidu call works.

By the way, this is not an openvidu call  issue. If you need help, write a post in OpenVidu Forum to allow be helped by the community.

**Comment by nirbhaydosi** [comment]
> The instructions I posted are not about docker, it’s about how run correctly openvidu call.
> 
> As the docs says, step 3, you need run openvidu-server container to do openvidu call works.
> 
> By the way, this is not an openvidu call issue. If you need help, write a post in OpenVidu Forum to allow be helped by the community.

Thank you.
