### ISSUE TITLE
on camera disable video hides but camera is still open

### ISSUE THREAD

**Issue by nedpuganti9** [OpenVidu/openvidu-call#65]
on camera disable video hides but camera is still open

**Comment by CSantosM** [comment]
Hi, 
openvidu-angular and openvidu-call have been updated and improved. Now **OpenVidu Components** come into play.

Visit the **OpenVidu Components** documentation [here](https://docs.openvidu.io/en/2.23.0/components/)
Visit the **OpenVidu Call** documentation [here](https://openvidu.io/openvidu-call)
