### ISSUE TITLE
TypeError: undefined is not an object (Evaluating 'navigator.mediaDevices.enumerateDevices')

### ISSUE THREAD

**Issue by paulohlimamaia** [OpenVidu/openvidu-call#66]
Hello,

when trying to use the demo [demos.openvidu.io/openvidu-call](https://demos.openvidu.io/openvidu-call) on iPhone 10.3.3, using Safari browser, i get the  error described bellow and are not able to use it.

`TypeError: undefined is not an object (Evaluating 'navigator.mediaDevices.enumerateDevices')`

This error also show up when using **openvidu-webcomponent** from openvidu-tutorials in the same iPhone.

There is something i'm doing wrong or this is a problem with the **openvidu-browser**?

**Comment by paulohlimamaia** [comment]
On iPhone 13 or greater it works flawlessly, but on older iPhones i get this error, there is something i could do to make it work?

**Comment by paulohlimamaia** [comment]
Just to clarify, i'm talking about the IOS version on the iPhone, not the iPhone model.

**Comment by CSantosM** [comment]
It looks like iOS 10.3.3 doesn’t support WebRTC. You can test with another WebRTC platform to verify if is an openvidu issue. For example WebRTC Samples https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by paulohlimamaia** [comment]
Got the same error on the link you provided. You are right, it does not support WebRTC. I hoped it would have a workaround but i guess not. Thanks for the support!
