### ISSUE TITLE
When a participant mutes someone in the conference, he should be muted for all participants.

### ISSUE THREAD

**Issue by salihy** [OpenVidu/openvidu-call#73]
When there are more than 2 participants and participant A mutes participant B, only A cannot hear B. Other participants can hear B. This should be fixed.

**Comment by CSantosM** [comment]
You're requesting a Moderatol role. It's not included in OpenVidu Call rigth now.

**Comment by salihy** [comment]
it's not a moderator role, just like in google meet, everyone in the meeting can mute everyone else.
