### ISSUE TITLE
openvidu-call inside electron and screen sharing

### ISSUE THREAD

**Issue by netvandal** [OpenVidu/openvidu-call#75]
Hello, 
We are playing with the idea to put electron around openvidu-call-front and basically we get it to work [we can share if someone is interested] . 
We are facing some problem supporting the screen share function, as we implemented a screen selector but passing the string "string:IDSCREENSELECTED" as we read in the documentation to the openViduWebRTCService.initPublisher(), but it doesn't work as expected.

In the logs we found that we have an error like 
`"DOMException: Could not start video source" `

and then we see 
`"Event 'accessDenied' triggered once by 'Publisher' OpenViduError {name: "DEVICE_ALREADY_IN_USE", message: "AbortError: Error starting screen capture"}" 

and finally 

`"[VideoRoomComponent] WARN:  ScreenShare: Access Denied "``

I suppose that with electron the access should be allowed already, so I'm missing something else?
Thankyou for any hint.

**Comment by CSantosM** [comment]
Hi, 
openvidu-angular and openvidu-call have been updated and improved. Now **OpenVidu Components** come into play.

Visit the **OpenVidu Components** documentation [here](https://docs.openvidu.io/en/2.23.0/components/)
Visit the **OpenVidu Call** documentation [here](https://openvidu.io/openvidu-call)
