### ISSUE TITLE
JavaScript heap out of memory when npx  ng serve --open 

### ISSUE THREAD

**Issue by soybean217** [OpenVidu/openvidu-call#79]
after run:
npx  ng serve --open 
JavaScript heap out of memory
and if use increase-memory-limit in openvidu-call-front , ng can not work .

Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/flex-layout/core : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/elements : es2015 as esm2015
Compiling @angular/flex-layout/extended : es2015 as esm2015
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/material/badge : es2015 as esm2015
Compiling @angular/material/card : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/menu : es2015 as esm2015
Compiling @angular/material/grid-list : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/material/progress-spinner : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @angular/material/sidenav : es2015 as esm2015
Compiling @angular/material/slider : es2015 as esm2015
Compiling @angular/material/toolbar : es2015 as esm2015
Compiling @angular/material/tooltip : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
Compiling elements-zone-strategy : es2015 as esm2015
Compiling @angular/flex-layout : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
68% building 789/805 modules 16 active ...idu-u20/openvidu-call/openvidu-call-front/node_modules/@angular/elements/__ivy_ngcc__/fesm2015/elements.js
<--- Last few GCs --->

[98099:0x4afb080]   101844 ms: Scavenge (reduce) 2041.0 (2053.7) -> 2040.5 (2054.0) MB, 3.7 / 0.0 ms  (average mu = 0.124, current mu = 0.001) allocation failure 
[98099:0x4afb080]   103230 ms: Mark-sweep (reduce) 2041.6 (2051.2) -> 2040.3 (2052.5) MB, 1384.5 / 0.0 ms  (average mu = 0.071, current mu = 0.013) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa04200 node::Abort() [ng serve --open]
 2: 0x94e4e9 node::FatalError(char const*, char const*) [ng serve --open]
 3: 0xb797be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng serve --open]
 4: 0xb79b37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng serve --open]
 5: 0xd343c5  [ng serve --open]
 6: 0xd34f4f  [ng serve --open]
 7: 0xd42fdb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng serve --open]
 8: 0xd46b9c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [ng serve --open]
 9: 0xd1527b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [ng serve --open]
10: 0x105b21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [ng serve --open]
11: 0x14011f9  [ng serve --open]
Aborted (core dumped)

**Comment by krishnahimself** [comment]
Temporary Fix:
node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng serve --aot --prod
Note: It takes longer time to compile than normal ng serve

**Comment by richard-dch** [comment]
@krishnahimself are you guys working on a fix for this ?, or if not what would be a permanent fix ?

**Comment by CSantosM** [comment]
Hi, 
openvidu-angular and openvidu-call have been updated and improved. Now **OpenVidu Components** come into play.

Visit the **OpenVidu Components** documentation [here](https://docs.openvidu.io/en/2.23.0/components/)
Visit the **OpenVidu Call** documentation [here](https://openvidu.io/openvidu-call)
