### ISSUE TITLE
Chat should show all messages

### ISSUE THREAD

**Issue by CSantosM** [OpenVidu/openvidu-call#9]
The chat component should show all messages to the last user.

**Comment by micaelgallego** [comment]
This should be implemented with some modifications in OpenVidu. There are two possibilities:
a) OpenVidu provides some kind of "notification message" storage. 
b) Applications implemented with OpenVidu have the ability to receive notifications exchanged between session connections. In that way, app can save the messages and resend again when a new client is connected.

**Comment by RuhulxD** [comment]
Is there any update regarding this?
Any way to get all of the signal-events (specially chats) to a external server(restapi server) to store chat history?

**Comment by micaelgallego** [comment]
You can receive all signals in a session using webhooks. 

Currently OpenVidu Call app is implemented as a client side app for demo purposes, but we plan to improve it in the following months to create a full-fledge videoconference application.

**Comment by RuhulxD** [comment]
Thank you for your answer. But still I did not find any document pointing to webhook for signals(chat). I only found that the webhooks can be registered only for these following events. "sessionCreated","sessionDestroyed","recordingStatusChanged" .. etc. 
Can you please point me out to any document by which I could catch the event related to signal .
[ProtocolElements.SENDMESSAGE_ROOM_METHOD](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/src/main/java/io/openvidu/server/rpc/RpcHandler.java)

**Comment by CSantosM** [comment]
https://openvidu.io/docs/reference-docs/openvidu-server-webhook/

**Comment by micaelgallego** [comment]
Sorry for the confusion, we are working on it but right now you CAN NOT RECEIVE SIGNAL EVENTS in a webhook.

**Comment by RuhulxD** [comment]
Thank you for all the efforts, you put in this project. That's disappointing, I need a way to store chat histories.
About to use  openvidu-pro in aws. I've also gone through the openvidu codes. I'm just curious, even if I implement any simple way to save this chat history, any possibility to upload custom openvidu-jar into AWS environment(openvidu-pro).
Also can you give us an idea that approximately when this feature will be available?

**Comment by micaelgallego** [comment]
The best way to implement that feature is that you manage the chat yourself instead of relaying to OpenVidu Session. In that way, the server, responsible to forward messages to all clients, can save them and send them to new users.

**Comment by RuhulxD** [comment]
Thank you for valuable suggestions. I'll explore that possibility.

**Comment by pabloFuente** [comment]
In master branch a new event called `signalEvent` is now available for the Webhook and CDR (see commit e8dd9bd8f4c739a83f26d9d9f6b59393e17337eb). This PR has not been merged becasue some minor changes were required, but the functionality is the expected one. Will be officially available in 2.17.0.

**Comment by RuhulxD** [comment]
Thank you so much for the effort. Eagerly waiting for this exciting feature. Regarding to signal events I have a suggestion which may significantly reduce the consumer server load. May be most of parties are not interested in all of the signalling event. Would be better if there are option to choose only the `chat` option. Please separate the  signalling event to `all` and `chat` or even better filter based on type: such as:   `signal:chat`.

 **Please Note that there would be so many of signal event which may drastically reduce the server performance in both openVidu and webhook server as for each of the signal event a http call will be generated :(.**
