### ISSUE TITLE
Yandex Browser support

### ISSUE THREAD

**Issue by AlexCollin** [OpenVidu/openvidu-call#92]
Hello! I using demo OpenVidu call
On Yandex browser i get error:

There was an error connecting to the session:
Browser Yandex Browser (version 21.5.0.625) for OS X is not supported in OpenVidu

MacOS 11.2.3 (20D91)
Mac mini (2018)

**Comment by CSantosM** [comment]
This is not an issue

**Comment by pabloFuente** [comment]
https://github.com/OpenVidu/openvidu-tutorials/issues/154
