### ISSUE TITLE
upgrade dependencies

### ISSUE THREAD

**Issue by buddudevelopers** [OpenVidu/openvidu-call#95]
It would be great if the project would be upgraded to angular material v12

**Comment by micaelgallego** [comment]
We are working on this right now.

**Comment by buddudevelopers** [comment]
Thank you @micaelgallego .

**Comment by CSantosM** [comment]
Hi, 
openvidu-angular and openvidu-call have been drastically updated and improved. Now **OpenVidu Components** come into play.

Visit the **OpenVidu Components** documentation [here](https://docs.openvidu.io/en/2.23.0/components/)
Visit the **OpenVidu Call** documentation [here](https://openvidu.io/openvidu-call)
